version: "3.7"

services:
  backend:
    build:
      context: backend
      dockerfile: prod.Dockerfile
    image: rsa-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: frontend
      dockerfile: prod.Dockerfile
    image: rsa-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
