version: 1

update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"

  - package_manager: "javascript"
    directory: "web_app/frontend"
    update_schedule: "weekly"
